import { useState, useMemo, useEffect } from 'react'
import { AreaChart, Area, BarChart, Bar, ScatterChart, Scatter, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, ComposedChart } from 'recharts'
import { Btn, Pill } from '../ui/index.jsx'
import { C, CHART_COLORS } from '../../theme.js'
import { isNumType } from './InputTab.jsx'
import { descriptive, freqTable, pearsonR, spearmanR, welchTTest, mannWhitneyU, linearRegression, logisticRegression, oneWayAnova, clean, isNormal, shapiroWilk, leveneTest } from '../../utils/statistics.js'
import { suggestModels } from '../../utils/modelAdvisor.js'
import { exportStatsCSV } from '../../utils/export.js'

const CTS=[{id:'area',label:'AREA',tip:'Xu hướng tích lũy'},{id:'line',label:'LINE',tip:'Xu hướng liên tục'},{id:'bar',label:'BAR',tip:'So sánh nhóm'},{id:'scatter',label:'SCATTER',tip:'Tương quan X-Y'},{id:'pie',label:'PIE',tip:'Tỷ lệ phân loại'},{id:'hist',label:'HIST',tip:'Phân phối/Normality'},{id:'box',label:'BOX',tip:'Median, Q1/Q3, IQR'},{id:'heatmap',label:'HEAT',tip:'Ma trận tương quan'}]
const DC=[...CHART_COLORS]
const TABS=[{id:'chart',label:'Chart',icon:'●',color:C.green},{id:'stats',label:'Stats',icon:'Σ',color:C.blue},{id:'corr',label:'Corr',icon:'◎',color:C.purple},{id:'model',label:'Model',icon:'⊕',color:C.orange},{id:'advisor',label:'Advisor',icon:'◆',color:C.gold}]
const hx=hex=>{const h=(hex||'00FA9A').replace('#','');return`${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)}`}

export function ChartTab({project,advisorModel,onAdvisorSelect}){
  const[tab,setTab]=useState('chart');const[ct,setCt]=useState('area');const[selVars,setSV]=useState(new Set());const[cc,setCC]=useState({});const[scf,setSCF]=useState(null);const[aav,setAAV]=useState(null)
  const[mdv,setMdv]=useState('');const[miv,setMiv]=useState(new Set());const[mgv,setMgv]=useState('')

  const sv=useMemo(()=>[...project.variables].sort((a,b)=>(a.order??0)-(b.order??0)),[project.variables])
  const nv=useMemo(()=>sv.filter(v=>isNumType(v.type)),[sv]);const cv=useMemo(()=>sv.filter(v=>v.type==='categorical'),[sv]);const bv=useMemo(()=>sv.filter(v=>v.type==='binary'),[sv])
  const chV=useMemo(()=>sv.filter(v=>v.type!=='image'),[sv]);const cnv=useMemo(()=>chV.filter(v=>isNumType(v.type)),[chV])
  const togV=vid=>setSV(p=>{const n=new Set(p);n.has(vid)?n.delete(vid):n.add(vid);return n})
  const gc=(vid,i)=>cc[vid]||DC[i%DC.length]

  // Smart default: auto-select first 2-3 numeric vars
  useEffect(()=>{if(selVars.size===0&&cnv.length>=1){const init=new Set(cnv.slice(0,Math.min(3,cnv.length)).map(v=>v.id));setSV(init)}},[cnv])

  // Advisor → Model
  useEffect(()=>{if(!advisorModel)return;setTab('model');const m=advisorModel;if(/logistic/i.test(m)&&bv.length>0){setMdv(bv[0].id);setMiv(new Set(nv.slice(0,3).map(v=>v.id)))}
    else if(/linear|ols/i.test(m)&&nv.length>=2){setMdv(nv[0].id);setMiv(new Set(nv.slice(1,4).map(v=>v.id)))}
    else if(/t-test|mann|welch/i.test(m)&&nv.length>0&&cv.length>0){setMdv(nv[0].id);setMgv(cv[0].id)}
    else if(/anova|kruskal/i.test(m)&&nv.length>0&&cv.length>0){setMdv(nv[0].id);setMgv(cv[0].id)}
    else if(/pearson|spearman|corr/i.test(m))setTab('corr');else if(/descriptive/i.test(m))setTab('stats')
    onAdvisorSelect(null)},[advisorModel])

  const snv=useMemo(()=>cnv.filter(v=>selVars.has(v.id)),[cnv,selVars])
  const vr=useMemo(()=>{const r={};snv.forEach(v=>{const vals=clean(project.rows.map(rr=>rr[v.id]));if(vals.length)r[v.id]={min:Math.min(...vals),max:Math.max(...vals),range:Math.max(...vals)-Math.min(...vals)}});return r},[snv,project.rows])
  const needMA=useMemo(()=>{const rs=Object.values(vr);if(rs.length<=1)return false;return Math.max(...rs.map(r=>r.range||1))/Math.max(Math.min(...rs.map(r=>r.range||1)),0.001)>3},[vr])
  const cd=useMemo(()=>project.rows.map((row,i)=>{const d={_idx:i+1};chV.forEach(v=>{d[v.id]=isNumType(v.type)&&row[v.id]!=null&&row[v.id]!==''&&row[v.id]!=='NA'?Number(row[v.id]):row[v.id]??''});return d}),[project.rows,chV])

  const aov=useMemo(()=>[...bv,...nv],[bv,nv])
  const depV=useMemo(()=>aov.find(v=>v.id===mdv),[aov,mdv])
  const mr=useMemo(()=>{if(!depV||(miv.size===0&&!mgv))return null;const il=cnv.filter(v=>miv.has(v.id)&&v.id!==depV.id);if(mgv){const gv=cv.find(v=>v.id===mgv);if(gv){const groups=[...new Set(project.rows.map(r=>r[gv.id]).filter(Boolean))];if(groups.length===2){const g1=project.rows.filter(r=>r[gv.id]===groups[0]).map(r=>r[depV.id]),g2=project.rows.filter(r=>r[gv.id]===groups[1]).map(r=>r[depV.id]);const n2=isNormal(g1)&&isNormal(g2)&&g1.length>=20&&g2.length>=20;const res=n2?welchTTest(g1,g2):mannWhitneyU(g1,g2);const lev=leveneTest([clean(g1),clean(g2)]);return res?{type:n2?'ttest':'mannwhitney',result:res,groups,levene:lev}:null}if(groups.length>=3){const gd=groups.map(g=>project.rows.filter(r=>r[gv.id]===g).map(r=>r[depV.id]));const res=oneWayAnova(gd);return res?{type:'anova',result:res}:null}}}if(!il.length)return null;if(depV.type==='binary'){const xv=il[0];const res=logisticRegression(project.rows.map(r=>r[xv.id]),project.rows.map(r=>r[depV.id]));return res?{type:'logistic',result:res,xName:xv.name}:null}const xv=il[0];const res=linearRegression(project.rows.map(r=>r[xv.id]),project.rows.map(r=>r[depV.id]));return res?{type:'linear',result:res,xName:xv.name}:null},[depV,miv,mgv,project.rows,cnv,cv])

  // ─── Chart ────
  const renderChart=()=>{if(!selVars.size)return<div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',color:'rgba(200,230,200,.25)',fontSize:12}}>Chọn biến để hiển thị</div>
    const sCat=chV.find(v=>selVars.has(v.id)&&v.type==='categorical')
    if(ct==='pie'){const v=sCat||chV.find(v2=>selVars.has(v2.id));if(!v)return<d1/>;const ft=freqTable(project.rows.map(r=>r[v.id]));const data=ft.map((f,i)=>({name:f.value,value:f.n,fill:DC[i%DC.length]}));return<RC><PieChart><Pie data={data} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius="65%" label={({name})=>name} stroke="rgba(7,7,15,.8)" strokeWidth={2}>{data.map((d,i)=><Cell key={i} fill={d.fill}/>)}</Pie><Tooltip contentStyle={ttS}/><Legend wrapperStyle={{fontSize:10}}/></PieChart></RC>}
    if(ct==='hist'){const v=snv[0];if(!v)return<d1/>;const vals=clean(project.rows.map(r=>r[v.id]));if(vals.length<2)return<d1/>;const mn=Math.min(...vals),mx=Math.max(...vals),nB=Math.min(Math.ceil(Math.sqrt(vals.length)),20),bW=(mx-mn)/nB||1;const bins=Array.from({length:nB},(_,i)=>({label:`${(mn+i*bW).toFixed(1)}`,count:0}));vals.forEach(v2=>{const idx=Math.min(Math.floor((v2-mn)/bW),nB-1);bins[idx].count++});return<RC><BarChart data={bins}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.06)"/><XAxis dataKey="label" tick={tk}/><YAxis tick={tk}/><Tooltip contentStyle={ttS}/><Bar dataKey="count" fill={gc(v.id,0)} fillOpacity={.7}/></BarChart></RC>}
    if(ct==='box'){const bd=snv.map((v,i)=>{const vals=[...clean(project.rows.map(r=>r[v.id]))].sort((a,b)=>a-b);if(vals.length<4)return null;const q1=vals[Math.floor(vals.length*.25)],med=vals[Math.floor(vals.length*.5)],q3=vals[Math.floor(vals.length*.75)],iqr=q3-q1;return{name:v.name,q1,med,q3,wL:Math.max(vals[0],q1-1.5*iqr),wH:Math.min(vals[vals.length-1],q3+1.5*iqr),color:gc(v.id,i)}}).filter(Boolean);if(!bd.length)return<d1/>;return<div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',gap:16,padding:8,overflow:'auto'}}>{bd.map((b,i)=><div key={i} style={{textAlign:'center'}}><svg width={50} height={160} viewBox="0 0 50 160">{(()=>{const lo=b.wL,hi=b.wH,rng=hi-lo||1,y=v=>140-((v-lo)/rng)*120+10;return<g><line x1={25} y1={y(b.wH)} x2={25} y2={y(b.q3)} stroke={b.color} strokeWidth={1.5}/><line x1={15} y1={y(b.wH)} x2={35} y2={y(b.wH)} stroke={b.color} strokeWidth={1.5}/><rect x={10} y={y(b.q3)} width={30} height={y(b.q1)-y(b.q3)} fill={`${b.color}22`} stroke={b.color} strokeWidth={1.5} rx={2}/><line x1={10} y1={y(b.med)} x2={40} y2={y(b.med)} stroke={b.color} strokeWidth={2.5}/><line x1={25} y1={y(b.q1)} x2={25} y2={y(b.wL)} stroke={b.color} strokeWidth={1.5}/><line x1={15} y1={y(b.wL)} x2={35} y2={y(b.wL)} stroke={b.color} strokeWidth={1.5}/></g>})()}</svg><div style={{fontSize:9,color:b.color}}>{b.name}</div></div>)}</div>}
    if(ct==='heatmap'){if(snv.length<2)return<d1/>;const cm=snv.map(v1=>snv.map(v2=>v1.id===v2.id?1:pearsonR(project.rows.map(r=>r[v1.id]),project.rows.map(r=>r[v2.id])).r));const cs=Math.min(38,220/snv.length);return<div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',overflow:'auto'}}><div><div style={{display:'flex',marginLeft:cs+6}}>{snv.map((v,i)=><div key={i} style={{width:cs,fontSize:7,color:'rgba(200,230,200,.5)',textAlign:'center',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{v.name}</div>)}</div>{cm.map((row,i)=><div key={i} style={{display:'flex',alignItems:'center'}}><div style={{width:cs+6,fontSize:7,color:'rgba(200,230,200,.5)',textAlign:'right',paddingRight:3,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{snv[i].name}</div>{row.map((r,j)=>{const abs=Math.abs(r);return<div key={j} style={{width:cs,height:cs,display:'flex',alignItems:'center',justifyContent:'center',background:`hsla(${r>=0?154:340},80%,50%,${abs*.5})`,border:'1px solid rgba(255,255,255,.05)',fontSize:7,color:abs>.4?'#fff':'rgba(200,230,200,.4)'}}>{isNaN(r)?'—':r.toFixed(2)}</div>})}</div>)}</div></div>}
    if(ct==='scatter'){if(snv.length<2)return<d1/>;const xv=snv[0],yv=snv[1];const sD=cd.filter(d=>d[xv.id]!=null&&d[yv.id]!=null&&typeof d[xv.id]==='number').map(d=>({x:d[xv.id],y:d[yv.id]}));return<RC><ScatterChart margin={{top:8,right:8,bottom:16,left:8}}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.06)"/><XAxis dataKey="x" name={xv.name} tick={tk} label={{value:xv.name,position:'bottom',fill:'rgba(200,230,200,.5)',fontSize:9}}/><YAxis dataKey="y" name={yv.name} tick={tk}/><Tooltip contentStyle={ttS}/><Scatter data={sD} fill={gc(yv.id,1)} fillOpacity={.7} r={4}/></ScatterChart></RC>}
    // Area/Line/Bar
    if(!snv.length)return<d1/>
    const useMA=needMA&&snv.length>1,actV=aav&&snv.find(v=>v.id===aav)?aav:snv[0]?.id
    return<RC><ComposedChart data={cd} margin={{top:5,right:5,bottom:5,left:5}}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.06)"/><XAxis dataKey="_idx" tick={tk}/>{useMA?snv.map((v,i)=>{const r=vr[v.id];return<YAxis key={v.id} yAxisId={v.id} domain={r?[Math.floor(r.min*.95),Math.ceil(r.max*1.05)]:['auto','auto']} hide={v.id!==actV} orientation={i%2===0?'left':'right'} tick={{fill:gc(v.id,i),fontSize:9}} axisLine={{stroke:gc(v.id,i)}}/>}):<YAxis yAxisId="s" tick={tk}/>}<Tooltip contentStyle={ttS} formatter={(val,name)=>[typeof val==='number'?val.toFixed(2):val,name]}/><Legend onClick={e=>{const vid=snv.find(v=>v.name===e.value)?.id;if(vid)setAAV(vid)}} wrapperStyle={{cursor:'pointer',fontSize:10}}/>{snv.map((v,i)=>{const vc=gc(v.id,i),yId=useMA?v.id:'s';return ct==='bar'?<Bar key={v.id} dataKey={v.id} name={v.name} fill={vc} fillOpacity={.7} yAxisId={yId}/>:ct==='line'?<Line key={v.id} dataKey={v.id} name={v.name} stroke={vc} strokeWidth={2} dot={{r:2,fill:vc}} yAxisId={yId} connectNulls/>:<Area key={v.id} dataKey={v.id} name={v.name} stroke={vc} fill={vc} fillOpacity={.12} strokeWidth={2} dot={{r:1.5,fill:vc}} yAxisId={yId} connectNulls/>})}</ComposedChart></RC>}

  // ─── Stats (with Shapiro-Wilk) ────
  const renderStats=()=><div style={{overflow:'auto',flex:1,padding:4}}>{nv.length===0&&<div style={{color:'rgba(200,230,200,.3)',padding:16}}>Chưa có biến số</div>}
    {nv.map(v=>{const d=descriptive(project.rows.map(r=>r[v.id]));if(!d)return null;return<div key={v.id} style={{marginBottom:10,padding:6,background:'rgba(255,255,255,.02)',border:'1px solid rgba(255,255,255,.06)',borderRadius:4}}><div style={{fontSize:10,color:C.blue,fontWeight:600,marginBottom:4}}>{v.name} {v.codeName&&<span style={{fontSize:8,color:'rgba(200,230,200,.2)'}}>({v.codeName})</span>}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(80px,1fr))',gap:3}}><Pill label="N" value={d.n} color={C.blue}/><Pill label="MEAN" value={d.mean} color={C.green}/><Pill label="SD" value={d.std} color={C.cyan}/><Pill label="MEDIAN" value={d.median} color={C.purple}/><Pill label="MIN" value={d.min}/><Pill label="MAX" value={d.max}/><Pill label="SKEW" value={d.skew} color={Math.abs(d.skew)>1?C.pink:C.green}/><Pill label="SHAPIRO-W" value={d.shapiroW??'—'} color={C.gold}/><Pill label="SHAPIRO-P" value={d.shapiroP??'—'} color={d.shapiroP>=0.05?C.green:C.pink}/><Pill label="NORMAL" value={d.normal?'Yes':'No'} color={d.normal?C.green:C.pink}/><Pill label="MISSING" value={d.missing} color={d.missing>0?C.gold:C.green}/></div></div>})}
    {cv.map(v=>{const ft=freqTable(project.rows.map(r=>r[v.id]));return<div key={v.id} style={{marginBottom:10,padding:6,background:'rgba(255,255,255,.02)',border:'1px solid rgba(255,255,255,.06)',borderRadius:4}}><div style={{fontSize:10,color:C.purple,fontWeight:600,marginBottom:4}}>{v.name}</div><div style={{display:'flex',flexWrap:'wrap',gap:3}}>{ft.map(f=><Pill key={f.value} label={f.value} value={`${f.n} (${f.pct}%)`} color={C.purple}/>)}</div></div>})}</div>

  // ─── Corr ────
  const renderCorr=()=>{if(nv.length<2)return<d1/>;return<div style={{overflow:'auto',flex:1,padding:4}}><table style={{borderCollapse:'collapse',fontSize:10,width:'100%'}}><thead><tr><th style={thS}></th>{nv.map(v=><th key={v.id} style={{...thS,color:C.purple}}>{v.name}</th>)}</tr></thead><tbody>{nv.map(v1=><tr key={v1.id}><td style={{...tdS,color:C.purple,fontWeight:600}}>{v1.name}</td>{nv.map(v2=>{if(v1.id===v2.id)return<td key={v2.id} style={{...tdS,color:C.green,fontWeight:700}}>1.00</td>;const fn=isNormal(project.rows.map(r=>r[v1.id]))?pearsonR:spearmanR;const res=fn(project.rows.map(r=>r[v1.id]),project.rows.map(r=>r[v2.id]));const abs=Math.abs(res.r);return<td key={v2.id} style={{...tdS,color:abs>.7?C.green:abs>.4?C.gold:'rgba(200,230,200,.5)',fontWeight:abs>.7?700:400}}>{isNaN(res.r)?'—':res.r.toFixed(3)}{res.p<.05&&'*'}</td>})}</tr>)}</tbody></table></div>}

  // ─── Model ────
  const renderModel=()=><div style={{overflow:'auto',flex:1,padding:4}}>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,marginBottom:8}}><div><label style={{fontSize:8,color:C.orange,fontFamily:'Orbitron',letterSpacing:'1px',display:'block',marginBottom:2}}>Y (OUTCOME)</label><select value={mdv} onChange={e=>setMdv(e.target.value)} style={{fontSize:11}}><option value="">— Chọn —</option>{aov.map(v=><option key={v.id} value={v.id}>{v.name} [{v.type}]</option>)}</select></div><div><label style={{fontSize:8,color:C.orange,fontFamily:'Orbitron',letterSpacing:'1px',display:'block',marginBottom:2}}>NHÓM</label><select value={mgv} onChange={e=>setMgv(e.target.value)} style={{fontSize:11}}><option value="">—</option>{cv.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></div></div>
    <div style={{marginBottom:8}}><label style={{fontSize:8,color:C.orange,fontFamily:'Orbitron',letterSpacing:'1px',display:'block',marginBottom:2}}>X (PREDICTORS)</label><div style={{display:'flex',flexWrap:'wrap',gap:3}}>{cnv.filter(v=>v.id!==mdv).map(v=><span key={v.id} onClick={()=>setMiv(p=>{const n=new Set(p);n.has(v.id)?n.delete(v.id):n.add(v.id);return n})} style={{padding:'2px 7px',borderRadius:3,fontSize:9,cursor:'pointer',background:miv.has(v.id)?'rgba(255,107,53,.18)':'rgba(255,255,255,.04)',border:`1px solid ${miv.has(v.id)?C.orange:'rgba(255,255,255,.1)'}`,color:miv.has(v.id)?C.orange:'rgba(200,230,200,.5)'}}>{v.name}</span>)}</div></div>
    {mr?<div style={{padding:8,background:'rgba(255,107,53,.04)',border:`1px solid ${C.orange}30`,borderRadius:5}}>
      <div style={{fontFamily:'Orbitron',fontSize:8,color:C.orange,letterSpacing:'2px',marginBottom:6}}>◎ {mr.type==='logistic'?'LOGISTIC':mr.type==='linear'?'LINEAR':mr.type==='ttest'?"WELCH T":mr.type==='mannwhitney'?'MANN-WHITNEY':mr.type==='anova'?'ANOVA':'—'}</div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(90px,1fr))',gap:4}}>
        {mr.type==='logistic'&&<><Pill label="OR" value={mr.result.or} color={C.orange}/><Pill label="ACC" value={`${mr.result.accuracy}%`} color={C.green}/><Pill label="SENS" value={`${mr.result.sensitivity}%`} color={C.blue}/><Pill label="SPEC" value={`${mr.result.specificity}%`} color={C.purple}/><Pill label="McFadden" value={mr.result.mcFaddenR2} color={C.gold}/></>}
        {mr.type==='linear'&&<><Pill label="β" value={mr.result.slope} color={C.blue}/><Pill label="R²" value={mr.result.r2} color={C.green}/><Pill label="RMSE" value={mr.result.rmse} color={C.orange}/><Pill label="P" value={mr.result.interpretation} color={mr.result.significant?C.green:C.pink}/></>}
        {mr.type==='ttest'&&<><Pill label="T" value={mr.result.t} color={C.pink}/><Pill label="DF" value={mr.result.df} color={C.blue}/><Pill label="P" value={mr.result.interpretation} color={mr.result.significant?C.green:C.pink}/><Pill label="Cohen d" value={mr.result.cohend} color={C.gold}/>{mr.levene&&<Pill label="Levene p" value={mr.levene.p} color={mr.levene.equalVariance?C.green:C.pink}/>}</>}
        {mr.type==='mannwhitney'&&<><Pill label="U" value={mr.result.U} color={C.pink}/><Pill label="Z" value={mr.result.z} color={C.blue}/><Pill label="P" value={mr.result.interpretation} color={mr.result.significant?C.green:C.pink}/><Pill label="r" value={mr.result.rbc} color={C.gold}/></>}
        {mr.type==='anova'&&<><Pill label="F" value={mr.result.F} color={C.orange}/><Pill label="P" value={mr.result.interpretation} color={mr.result.significant?C.green:C.pink}/><Pill label="η²" value={mr.result.eta2} color={C.gold}/></>}
      </div></div>:<div style={{padding:12,color:'rgba(200,230,200,.2)',fontSize:11,textAlign:'center'}}>{mdv?'Chọn X hoặc nhóm':'Chọn Y + X'}</div>}</div>

  // ─── Advisor ────
  const renderAdvisor=()=>{const adv=suggestModels(sv,project.rows);const models=adv.models||adv;const gw=adv.globalWarns||[];return<div style={{overflow:'auto',flex:1,padding:4}}>
    {gw.length>0&&<div style={{marginBottom:8,padding:6,background:'rgba(255,45,120,.06)',border:`1px solid ${C.pink}30`,borderRadius:4}}><div style={{fontFamily:'Orbitron',fontSize:8,color:C.pink,letterSpacing:'2px',marginBottom:3}}>⚠ CẢNH BÁO</div>{gw.map((w,i)=><div key={i} style={{fontSize:10,color:C.pink,marginBottom:1}}>• {w}</div>)}</div>}
    {(Array.isArray(models)?models:[]).map((m,i)=><div key={i} style={{marginBottom:10,padding:8,background:`rgba(${hx(m.color)},.04)`,border:`1px solid ${m.color}22`,borderRadius:5}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:4}}><div><span style={{fontFamily:'Orbitron',fontSize:10,color:m.color,fontWeight:700}}>{m.name}</span><span style={{fontSize:8,color:'rgba(200,230,200,.3)',marginLeft:4}}>{m.category}</span></div><div style={{display:'flex',alignItems:'center',gap:3}}><div style={{width:36,height:4,background:'rgba(255,255,255,.08)',borderRadius:3,overflow:'hidden'}}><div style={{width:`${m.confidence}%`,height:'100%',background:m.color}}/></div><span style={{fontSize:8,color:m.color,fontFamily:'Orbitron'}}>{m.confidence}%</span></div></div>
      <div style={{fontSize:10,color:'rgba(200,230,200,.55)',marginBottom:4,lineHeight:1.4}}>{m.rationale}</div>
      {m.assumptions?.map((a,j)=><div key={j} style={{fontSize:9,color:a.ok?'rgba(0,250,154,.6)':'rgba(255,45,120,.6)',display:'flex',gap:3,marginBottom:1}}><span>{a.ok?'✓':'✗'}</span><span>{a.text}</span></div>)}
      <div style={{display:'flex',flexWrap:'wrap',gap:2,marginTop:3,marginBottom:3}}>{m.outputs?.map((o,j)=><span key={j} style={{fontSize:8,padding:'1px 5px',borderRadius:2,background:`rgba(${hx(m.color)},.08)`,color:m.color,border:`1px solid ${m.color}18`}}>{o}</span>)}</div>
      {m.warns?.length>0&&m.warns.map((w,j)=><div key={j} style={{fontSize:9,color:C.pink}}>{w}</div>)}
      {m.nextSteps?.length>0&&<div style={{borderTop:'1px solid rgba(255,255,255,.05)',paddingTop:3,marginTop:3}}>{m.nextSteps.map((s,j)=><div key={j} style={{fontSize:9,color:'rgba(200,230,200,.35)'}}>→ {s}</div>)}</div>}
      <div style={{marginTop:4}}><span onClick={()=>onAdvisorSelect(m.name)} style={{padding:'2px 8px',borderRadius:3,fontSize:8,cursor:'pointer',fontFamily:'Orbitron',letterSpacing:'1px',background:`rgba(${hx(m.color)},.12)`,border:`1px solid ${m.color}40`,color:m.color}}>▶ Chạy</span></div>
    </div>)}</div>}

  // ═══ MAIN ═══
  return<div style={{height:'100%',display:'flex',flexDirection:'column',overflow:'hidden',padding:5}}>
    <div style={{display:'flex',gap:2,marginBottom:3,alignItems:'center',flexShrink:0}}>{TABS.map(t=><span key={t.id} onClick={()=>setTab(t.id)} style={{padding:'2px 7px',borderRadius:3,fontSize:8,cursor:'pointer',fontFamily:'Orbitron',letterSpacing:'1px',background:tab===t.id?`rgba(${hx(t.color)},.15)`:'transparent',border:`1px solid ${tab===t.id?t.color:'rgba(255,255,255,.06)'}`,color:tab===t.id?t.color:'rgba(200,230,200,.4)'}}>{t.icon} {t.label}</span>)}<div style={{flex:1}}/><Btn small onClick={()=>exportStatsCSV(project)} color={C.gold}>↓CSV</Btn></div>
    {tab==='chart'&&<><div style={{display:'flex',gap:2,marginBottom:2,flexShrink:0,flexWrap:'wrap'}}>{CTS.map(c=><span key={c.id} onClick={()=>setCt(c.id)} title={c.tip} style={{padding:'1px 5px',borderRadius:3,fontSize:7,cursor:'pointer',fontFamily:'Orbitron',letterSpacing:'.5px',background:ct===c.id?'rgba(0,250,154,.15)':'rgba(255,255,255,.04)',border:`1px solid ${ct===c.id?C.green:'rgba(255,255,255,.06)'}`,color:ct===c.id?C.green:'rgba(200,230,200,.35)',whiteSpace:'nowrap'}}>{c.label}</span>)}</div>
      <div style={{display:'flex',flexWrap:'wrap',gap:2,marginBottom:2,flexShrink:0,maxHeight:50,overflowY:'auto'}}>{chV.filter(v=>v.type!=='image').map((v,vi)=>{const isSel=selVars.has(v.id),vc=gc(v.id,vi);return<span key={v.id} style={{display:'inline-flex',alignItems:'center',gap:2,position:'relative'}}><span onClick={()=>togV(v.id)} style={{padding:'1px 5px',borderRadius:3,fontSize:8,cursor:'pointer',background:isSel?`${vc}22`:'rgba(255,255,255,.04)',border:`1px solid ${isSel?vc:'rgba(255,255,255,.06)'}`,color:isSel?vc:'rgba(200,230,200,.35)'}}>{v.name}</span>{isSel&&<span onClick={()=>setSCF(scf===v.id?null:v.id)} style={{width:9,height:9,borderRadius:'50%',background:vc,cursor:'pointer',flexShrink:0}}/>}{scf===v.id&&<div style={{position:'absolute',top:'100%',left:0,zIndex:100,background:'#0D0D1F',border:'1px solid rgba(0,250,154,.3)',borderRadius:3,padding:3,display:'flex',flexWrap:'wrap',gap:2,width:100,marginTop:1}}>{DC.map(c=><span key={c} onClick={()=>{setCC(p=>({...p,[v.id]:c}));setSCF(null)}} style={{width:14,height:14,borderRadius:'50%',background:c,cursor:'pointer',outline:cc[v.id]===c?'2px solid #fff':'none'}}/>)}</div>}</span>})}</div>
      {needMA&&snv.length>1&&<div style={{fontSize:7,color:C.gold,marginBottom:1,flexShrink:0,opacity:.7}}>⚡ Y-axis độc lập — click legend chuyển</div>}
    </>}
    <div style={{flex:1,minHeight:0,overflow:'hidden',display:'flex',flexDirection:'column'}}>{tab==='chart'&&renderChart()}{tab==='stats'&&renderStats()}{tab==='corr'&&renderCorr()}{tab==='model'&&renderModel()}{tab==='advisor'&&renderAdvisor()}</div>
  </div>
}

const d1=()=><div style={{padding:16,color:'rgba(200,230,200,.3)',fontSize:11,textAlign:'center'}}>Chọn biến phù hợp</div>
const RC=({children})=><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer>
const tk={fill:'rgba(200,230,200,.4)',fontSize:9}
const ttS={background:'rgba(5,5,18,.96)',border:'1px solid rgba(0,250,154,.4)',borderRadius:4,fontSize:10}
const thS={padding:'4px 6px',textAlign:'left',fontSize:10,borderBottom:'1px solid rgba(191,95,255,.2)',color:'rgba(200,230,200,.5)',fontWeight:400}
const tdS={padding:'3px 6px',fontSize:11,borderBottom:'1px solid rgba(191,95,255,.05)'}
