import { clean, isNormal, pearsonR, mean, std, skewness, kurtosis, shapiroWilk, leveneTest } from './statistics.js'
import { C } from '../theme.js'
export function suggestModels(variables,rows){
  const num=variables.filter(v=>['number','integer','percent','ordinal'].includes(v.type)),bin=variables.filter(v=>v.type==='binary'),cat=variables.filter(v=>v.type==='categorical'),ord=variables.filter(v=>v.type==='ordinal'),n=rows.length
  const normalMap={};num.forEach(v=>{normalMap[v.id]=isNormal(rows.map(r=>r[v.id]))&&clean(rows.map(r=>r[v.id])).length>=20})
  const catGroups={};cat.forEach(v=>{catGroups[v.id]=new Set(rows.map(r=>r[v.id]).filter(Boolean)).size})
  const collinearPairs=[];if(num.length>=2){for(let i=0;i<num.length;i++)for(let j=i+1;j<num.length;j++){const r=pearsonR(rows.map(r2=>r2[num[i].id]),rows.map(r2=>r2[num[j].id]));if(Math.abs(r.r)>0.8)collinearPairs.push([num[i].name,num[j].name,r.r])}}
  const outlierVars=[];num.forEach(v=>{const vals=clean(rows.map(r=>r[v.id]));if(vals.length<10)return;if(Math.abs(skewness(vals))>2||Math.abs(kurtosis(vals))>7)outlierVars.push(v.name)})
  const highMissing=variables.filter(v=>{const miss=rows.filter(r=>r[v.id]===undefined||r[v.id]===''||r[v.id]===null||r[v.id]==='NA').length;return miss/Math.max(n,1)>0.2}).map(v=>v.name)
  const results=[]
  // Logistic
  if(bin.length>0&&num.length>=1){const bv=bin[0],vals=rows.map(r=>Number(r[bv.id])).filter(v=>!isNaN(v)),pos=vals.filter(v=>v===1).length,neg=vals.length-pos,bal=pos>0&&vals.length>pos?Math.min(pos,neg)/Math.max(pos,neg):0,epp=Math.min(pos,neg)/num.length;const warns=[];if(n<30)warns.push('⚠ N < 30');if(epp<10)warns.push(`⚠ EPP = ${epp.toFixed(1)} (cần ≥10)`);if(bal<.2)warns.push(`⚠ Imbalanced: ${pos}/${neg}`);if(collinearPairs.length)warns.push('⚠ Đa cộng tuyến');results.push({name:'Logistic Regression',color:C.green,confidence:epp>=10&&n>=100?95:epp>=5&&n>=30?78:45,category:'Đa biến — Outcome nhị phân',rationale:`"${bv.name}" (${pos}/${neg}) + ${num.length} predictors`,assumptions:[{ok:n>=30,text:`N=${n}`},{ok:bal>=.2,text:`Balance ${(bal*100).toFixed(0)}%`},{ok:epp>=10,text:`EPP=${epp.toFixed(1)}`}],outputs:['OR','AUC','Sens/Spec','McFadden R²'],warns,nextSteps:['Cross-validation','VIF kiểm tra','ROC curve']})}
  // Linear
  if(num.length>=2){const allN=num.every(v=>normalMap[v.id]);results.push({name:'Linear Regression',color:C.blue,confidence:n>=30&&allN?90:n>=20?72:45,category:'Đa biến — Outcome liên tục',rationale:`${num.length} biến số → β, R²`,assumptions:[{ok:n>=20,text:`N=${n}`},{ok:allN,text:allN?'Residuals chuẩn':'Cần kiểm tra'}],outputs:['β','R²','RMSE','p-value'],warns:n<20?['⚠ N < 20']:[],nextSteps:['Residual plot','Q-Q plot']})}
  // T-test / Mann-Whitney
  if(cat.length>0&&num.length>=1){const cv2=cat.find(v=>catGroups[v.id]===2);if(cv2){const nv=num[0],groups=[...new Set(rows.map(r=>r[cv2.id]).filter(Boolean))],g1=clean(rows.filter(r=>r[cv2.id]===groups[0]).map(r=>r[nv.id])),g2=clean(rows.filter(r=>r[cv2.id]===groups[1]).map(r=>r[nv.id])),bothN=g1.length>=20&&g2.length>=20&&isNormal(g1)&&isNormal(g2),method=bothN?"Welch's t-test":'Mann-Whitney U';const lev=leveneTest([g1,g2]);results.push({name:method,color:C.pink,confidence:n>=30?90:n>=15?75:55,category:'So sánh 2 nhóm',rationale:`"${nv.name}" giữa "${cv2.name}" (${groups.join(' vs ')})`,assumptions:[{ok:g1.length>=10&&g2.length>=10,text:`N: ${g1.length} vs ${g2.length}`},{ok:bothN,text:bothN?'Chuẩn':'Non-parametric'},{ok:lev?.equalVariance!==false,text:lev?`Levene p=${lev.p} ${lev.equalVariance?'✓':'✗'}`:'—'}],outputs:bothN?['t','df','p','Cohen d','95% CI']:['U','z','p','rank-biserial r'],warns:[],nextSteps:['Effect size interpretation']})}
  // ANOVA
  const cvM=cat.find(v=>catGroups[v.id]>=3);if(cvM){results.push({name:'One-way ANOVA / Kruskal-Wallis',color:C.orange,confidence:n>=30?85:65,category:'So sánh nhiều nhóm',rationale:`"${num[0].name}" giữa ${catGroups[cvM.id]} nhóm`,assumptions:[{ok:n>=30,text:`N=${n}`}],outputs:['F / H','p','η²','Post-hoc'],warns:[],nextSteps:['Tukey HSD / Dunn test']})}}
  // Correlation
  if(num.length>=2){const allN=num.every(v=>normalMap[v.id]);results.push({name:allN?'Pearson':'Spearman',color:C.purple,confidence:n>=20?92:n>=10?75:55,category:'Tương quan',rationale:`${num.length} biến → ma trận tương quan`,assumptions:[{ok:n>=10,text:`N=${n}`},{ok:allN,text:allN?'Pearson':'Spearman'}],outputs:['r','p','Heatmap'],warns:collinearPairs.length?[`Collinear: ${collinearPairs.length} cặp`]:[],nextSteps:['Scatter plots','Partial correlation']})}
  // Chi-square
  if(cat.length>=2||cat.length>=1&&bin.length>=1){results.push({name:'Chi-Square / Fisher',color:C.gold,confidence:n>=20?85:60,category:'2 biến phân loại',rationale:'Kiểm tra liên quan giữa 2 biến phân loại',assumptions:[{ok:n>=20,text:`N=${n}`}],outputs:['χ²','p',"Cramér's V"],warns:[],nextSteps:["Standardized residuals"]})}
  // Descriptive always
  results.push({name:'Descriptive Statistics',color:C.cyan,confidence:100,category:'Bước 1 — Mô tả',rationale:'Luôn bắt đầu với mô tả. Shapiro-Wilk test, Q-Q assessment.',assumptions:[{ok:true,text:'Luôn áp dụng'}],outputs:['Mean±SD','Median[IQR]','Shapiro-Wilk','Freq table'],warns:[],nextSteps:['Tab Stats có sẵn descriptive']})
  const globalWarns=[];if(highMissing.length)globalWarns.push(`Missing >20%: ${highMissing.join(', ')}`);if(n<10)globalWarns.push('N < 10');if(outlierVars.length)globalWarns.push(`Outlier: ${outlierVars.join(', ')}`)
  return{models:results.sort((a,b)=>b.confidence-a.confidence),globalWarns,collinearPairs,outlierVars,highMissing}
}
