import { useState, useEffect, useRef } from 'react'
import { onAuthStateChanged, signOut, updatePassword, reauthenticateWithCredential, EmailAuthProvider } from 'firebase/auth'
import { ref, onValue, push, update, remove } from 'firebase/database'
import { auth, db } from './firebase.js'
import { LoginPage, RegisterPage } from './components/AuthPages.jsx'
import { AdminPage } from './components/AdminPage.jsx'
import { InputTab } from './components/tabs/InputTab.jsx'
import { TableTab } from './components/tabs/TableTab.jsx'
import { ChartTab } from './components/tabs/ChartTab.jsx'
import { Btn, HoloPanel } from './components/ui/index.jsx'
import { C } from './theme.js'
import { padPw } from './utils/pwUtils.js'
import './styles/global.css'

function seedDemo(uid){const vars=[{name:'ID Mẫu',codeName:'sample_id',type:'id',order:0},{name:'Tên BN',codeName:'patient_name',type:'name',order:1},{name:'Tuổi',codeName:'age',type:'number',order:2},{name:'Giới tính',codeName:'sex',type:'categorical',order:3},{name:'HA tâm thu',codeName:'sbp',type:'number',order:4},{name:'HA tâm trương',codeName:'dbp',type:'number',order:5},{name:'Biến cố',codeName:'event',type:'binary',order:6}];const rows=[['BN001','Nguyễn Văn A',45,'Nam',130,85,0],['BN002','Trần Thị B',52,'Nữ',145,92,1],['BN003','Lê Văn C',38,'Nam',120,78,0],['BN004','Phạm Thị D',61,'Nữ',165,100,1],['BN005','Hoàng Văn E',47,'Nam',138,88,0],['BN006','Ngô Thị F',55,'Nữ',152,95,1]];push(ref(db,'projects'),{name:'DEMO • Huyết Áp',ownerUid:uid,createdAt:Date.now(),parentId:null}).then(pRef=>{const keys=vars.map(v=>push(ref(db,`projects/${pRef.key}/variables`),v).key);setTimeout(()=>{rows.forEach(r=>{const obj={createdAt:Date.now()};keys.forEach((k,i)=>{obj[k]=r[i]});push(ref(db,`projects/${pRef.key}/rows`),obj)})},700)})}

function ChangePwModal({user,onClose}){const[oldPw,setOldPw]=useState('');const[newPw,setNewPw]=useState('');const[newPw2,setNewPw2]=useState('');const[err,setErr]=useState('');const[ok,setOk]=useState(false);const[loading,setLoading]=useState(false);const go=async()=>{if(!oldPw||!newPw)return setErr('Điền đầy đủ');if(newPw!==newPw2)return setErr('Mật khẩu mới không khớp');setLoading(true);setErr('');try{const cred=EmailAuthProvider.credential(user.email,padPw(oldPw));await reauthenticateWithCredential(auth.currentUser,cred);await updatePassword(auth.currentUser,padPw(newPw));setOk(true);setTimeout(onClose,1500)}catch(e){setErr(e.code==='auth/wrong-password'?'Sai mật khẩu':'Lỗi: '+e.message)}finally{setLoading(false)}};return(<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.82)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:2000}}><div className="fade-in" style={{width:380,maxWidth:'90vw'}}><HoloPanel style={{padding:28}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}><div style={{fontFamily:'Orbitron',fontSize:11,color:C.gold}}>◈ ĐỔI MẬT KHẨU</div><span onClick={onClose} style={{color:'rgba(200,230,200,.4)',cursor:'pointer',fontSize:20}}>✕</span></div>{ok?<div style={{textAlign:'center',padding:20,color:C.green}}>✓ Thành công</div>:<>{[['MẬT KHẨU HIỆN TẠI',oldPw,setOldPw],['MẬT KHẨU MỚI',newPw,setNewPw],['XÁC NHẬN',newPw2,setNewPw2]].map(([l,v,s])=><div key={l} style={{marginBottom:14}}><label style={{fontSize:13,color:'rgba(200,230,200,.5)',display:'block',marginBottom:5}}>{l}</label><input type="password" value={v} onChange={e=>s(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/></div>)}{err&&<div style={{color:C.pink,fontSize:13,marginBottom:14,padding:'7px 12px',background:'rgba(255,45,120,.07)',borderRadius:4}}>{err}</div>}<div style={{display:'flex',gap:10}}><Btn onClick={go} color={C.gold} disabled={loading} style={{flex:1,justifyContent:'center',padding:'10px',fontSize:13}}>{loading?'◌ ...':'Xác nhận'}</Btn><Btn onClick={onClose} color={C.pink} outline style={{padding:'10px 16px',fontSize:13}}>Hủy</Btn></div></>}</HoloPanel></div></div>)}

function Divider({onDrag,vertical=false}){const dr=useRef(false),st=useRef(0);const md=e=>{dr.current=true;st.current=vertical?e.clientY:e.clientX;const mv=ev=>{if(!dr.current)return;const d=vertical?ev.clientY-st.current:ev.clientX-st.current;st.current=vertical?ev.clientY:ev.clientX;onDrag(d)};const up=()=>{dr.current=false;window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up)};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up)};return<div onMouseDown={md} style={{[vertical?'height':'width']:6,flexShrink:0,cursor:vertical?'row-resize':'col-resize',background:'rgba(255,255,255,.03)',display:'flex',alignItems:'center',justifyContent:'center'}} onMouseEnter={e=>e.currentTarget.style.background='rgba(0,250,154,.12)'} onMouseLeave={e=>e.currentTarget.style.background='rgba(255,255,255,.03)'}><div style={{[vertical?'width':'height']:30,[vertical?'height':'width']:3,background:'rgba(255,255,255,.12)',borderRadius:2}}/></div>}

const PB={input:C.cyan,table:C.purple,chart:C.green}
const Panel=({children,pk,style={}})=><div style={{display:'flex',flexDirection:'column',overflow:'hidden',background:`linear-gradient(135deg,rgba(${pk==='input'?'0,229,255':pk==='table'?'191,95,255':'0,250,154'},.015) 0%,rgba(7,7,15,.98) 100%)`,border:`1px solid ${PB[pk]}20`,borderRadius:7,...style}}>{children}</div>

function SidebarItem({p,activePid,setActivePid,onDelete,level=0,children:ch}){const[open,setOpen]=useState(true);const[hov,setHov]=useState(false);const hc=ch&&ch.length>0;return<div><div onClick={()=>setActivePid(p.id)} onMouseEnter={e=>{setHov(true);if(p.id!==activePid)e.currentTarget.style.background='rgba(0,250,154,.03)'}} onMouseLeave={e=>{setHov(false);if(p.id!==activePid)e.currentTarget.style.background='transparent'}} style={{padding:`8px ${14+level*12}px`,cursor:'pointer',borderLeft:p.id===activePid?`2px solid ${C.green}`:'2px solid transparent',background:p.id===activePid?'rgba(0,250,154,.07)':'transparent',display:'flex',alignItems:'center',gap:6,transition:'all .15s'}}>{hc&&<span onClick={e=>{e.stopPropagation();setOpen(o=>!o)}} style={{color:'rgba(200,230,200,.35)',fontSize:10,userSelect:'none'}}>{open?'▾':'▸'}</span>}<div style={{flex:1,minWidth:0}}><div style={{fontSize:13,color:p.id===activePid?C.green:'rgba(200,230,200,.55)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{level>0&&<span style={{color:'rgba(200,230,200,.2)',marginRight:5}}>└</span>}{p.name}</div><div style={{fontSize:11,color:'rgba(200,230,200,.2)'}}>{(p.rows||[]).length} dòng · {(p.variables||[]).length} biến</div></div>{hov&&<span onClick={e=>{e.stopPropagation();onDelete(p.id,p.name)}} style={{color:'rgba(255,45,120,.4)',cursor:'pointer',fontSize:12,padding:'2px 4px',flexShrink:0}} onMouseEnter={e=>e.currentTarget.style.color=C.pink} onMouseLeave={e=>e.currentTarget.style.color='rgba(255,45,120,.4)'}>✕</span>}</div>{open&&hc&&ch.map(s=><SidebarItem key={s.id} p={s} activePid={activePid} setActivePid={setActivePid} onDelete={onDelete} level={level+1} children={[]}/>)}</div>}

function NewProjectModal({projects,uid,onClose}){const[name,setName]=useState('');const[parentId,setParentId]=useState('');const[saving,setSaving]=useState(false);const tp=projects.filter(p=>!p.parentId);const go=async()=>{if(!name.trim())return;setSaving(true);try{await push(ref(db,'projects'),{name:name.trim(),ownerUid:uid,createdAt:Date.now(),parentId:parentId||null});onClose()}catch(e){alert(e.message)}finally{setSaving(false)}};return<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.82)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:2000}}><div className="fade-in" style={{width:380,maxWidth:'90vw'}}><HoloPanel style={{padding:26}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:22}}><div style={{fontFamily:'Orbitron',fontSize:11,color:C.green}}>+ PROJECT MỚI</div><span onClick={onClose} style={{color:'rgba(200,230,200,.4)',cursor:'pointer',fontSize:20}}>✕</span></div><div style={{marginBottom:16}}><label style={{fontSize:13,color:'rgba(200,230,200,.5)',display:'block',marginBottom:6}}>TÊN PROJECT</label><input value={name} onChange={e=>setName(e.target.value)} autoFocus placeholder="Nghiên cứu..." onKeyDown={e=>e.key==='Enter'&&go()}/></div><div style={{marginBottom:22}}><label style={{fontSize:13,color:'rgba(200,230,200,.5)',display:'block',marginBottom:6}}>THUỘC PROJECT LỚN</label><select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">— Độc lập —</option>{tp.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div style={{display:'flex',gap:10}}><Btn onClick={go} disabled={!name.trim()||saving} style={{flex:1,justifyContent:'center',padding:'10px',fontSize:13}}>{saving?'◌ ...':'Tạo project'}</Btn><Btn onClick={onClose} color={C.pink} outline style={{padding:'10px 16px',fontSize:13}}>Hủy</Btn></div></HoloPanel></div></div>}

const PTog=({label,color,active,onClick})=><span onClick={onClick} title={active?`Ẩn ${label}`:`Hiện ${label}`} style={{padding:'3px 8px',borderRadius:4,fontSize:8,cursor:'pointer',fontFamily:'Orbitron',letterSpacing:'1px',userSelect:'none',background:active?`${color}22`:'rgba(255,255,255,.03)',border:`1px solid ${active?color:'rgba(255,255,255,.06)'}`,color:active?color:'rgba(200,230,200,.25)',transition:'all .2s'}}>{label}</span>

export default function App(){
  const[authUser,setAuthUser]=useState(undefined);const[userMeta,setUserMeta]=useState(null);const[page,setPage]=useState('login');const[projects,setProjects]=useState([]);const[activePid,setActivePid]=useState(null);const[sidebar,setSidebar]=useState(true);const[showNewProj,setShowNewProj]=useState(false);const[showChangePw,setShowChangePw]=useState(false);const[showUserMenu,setShowUserMenu]=useState(false)
  const[showInput,setShowInput]=useState(true);const[showTable,setShowTable]=useState(true);const[showChart,setShowChart]=useState(true)
  const[advisorModel,setAdvisorModel]=useState(null)
  const containerRef=useRef(null);const userMenuRef=useRef(null);const[leftW,setLeftW]=useState(240);const[topH,setTopH]=useState(0)
  useEffect(()=>{setTopH(Math.round((window.innerHeight-48)*0.42))},[])
  useEffect(()=>{if(!showUserMenu)return;const h=e=>{if(userMenuRef.current&&!userMenuRef.current.contains(e.target))setShowUserMenu(false)};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h)},[showUserMenu])
  useEffect(()=>onAuthStateChanged(auth,async u=>{setAuthUser(u);if(!u){setPage('login');setUserMeta(null);return}const snap=await new Promise(res=>onValue(ref(db,`users/${u.uid}`),res,{onlyOnce:true}));const meta=snap.exists()?snap.val():{name:u.email,role:'user'};setUserMeta({uid:u.uid,...meta,email:u.email});setPage(meta.role==='admin'?'admin':'app')}),[])
  useEffect(()=>{if(!authUser||page!=='app')return;return onValue(ref(db,'projects'),snap=>{if(!snap.exists()){setProjects([]);return}const list=Object.entries(snap.val()).map(([id,v])=>({id,name:v.name,ownerUid:v.ownerUid,parentId:v.parentId||null,variables:v.variables?Object.entries(v.variables).map(([vid,vv])=>({id:vid,...vv})):[],rows:v.rows?Object.entries(v.rows).map(([rid,rv])=>({id:rid,...rv})):[]}));setProjects(list);setActivePid(p=>p||(list[0]?.id??null))})},[authUser,page])
  const logout=()=>signOut(auth);const activeProject=projects.find(p=>p.id===activePid)
  const deleteProject=(pid,pname)=>{if(!window.confirm(`Xóa project "${pname}"?`))return;remove(ref(db,`projects/${pid}`));if(activePid===pid)setActivePid(null)}

  if(authUser===undefined)return<div style={{minHeight:'100vh',background:'#07070F',display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:14}}><div style={{fontFamily:'Orbitron',fontSize:11,color:C.green,letterSpacing:'4px',opacity:.5}}>INITIALIZING...</div><div style={{width:200,height:2,background:'rgba(0,250,154,.1)',borderRadius:1,overflow:'hidden'}}><div style={{height:'100%',background:C.green,width:'40%',animation:'loadbar 1.4s ease-in-out infinite',borderRadius:1}}/></div></div>
  if(page==='login')return<LoginPage onSwitch={setPage}/>
  if(page==='register')return<RegisterPage onSwitch={setPage}/>
  if(page==='admin')return<AdminPage user={userMeta} onLogout={logout}/>
  const topP=projects.filter(p=>!p.parentId),subOf=pid=>projects.filter(p=>p.parentId===pid)

  return<div style={{height:'100vh',display:'flex',flexDirection:'column',background:'#07070F',overflow:'hidden'}}>
    <div style={{height:48,background:'rgba(0,0,0,.65)',borderBottom:'1px solid rgba(255,255,255,.07)',display:'flex',alignItems:'center',padding:'0 14px',flexShrink:0,gap:10}}>
      <span onClick={()=>setSidebar(s=>!s)} style={{color:C.green,cursor:'pointer',fontSize:16,opacity:.6,userSelect:'none',padding:'4px 6px'}} onMouseEnter={e=>e.currentTarget.style.opacity='1'} onMouseLeave={e=>e.currentTarget.style.opacity='.6'}>☰</span>
      <div style={{fontFamily:'Orbitron',fontSize:14,fontWeight:700,color:C.green,letterSpacing:'2px',textShadow:'0 0 18px rgba(0,250,154,.38)'}}>RTRE</div>
      <span style={{fontFamily:'Orbitron',fontSize:8,color:'rgba(0,250,154,.28)',letterSpacing:'4px'}}>RESEARCH ENGINE</span>
      <div style={{display:'flex',gap:4,marginLeft:16}}>
        <PTog label="INPUT" color={C.cyan} active={showInput} onClick={()=>setShowInput(s=>!s)}/>
        <PTog label="TABLE" color={C.purple} active={showTable} onClick={()=>setShowTable(s=>!s)}/>
        <PTog label="CHART" color={C.green} active={showChart} onClick={()=>setShowChart(s=>!s)}/>
      </div>
      <div style={{flex:1}}/>
      <div ref={userMenuRef} style={{position:'relative'}}>
        <div onClick={()=>setShowUserMenu(s=>!s)} style={{display:'flex',alignItems:'center',gap:8,cursor:'pointer',padding:'5px 10px',borderRadius:5,background:showUserMenu?'rgba(255,255,255,.08)':'transparent'}} onMouseEnter={e=>e.currentTarget.style.background='rgba(255,255,255,.06)'} onMouseLeave={e=>e.currentTarget.style.background=showUserMenu?'rgba(255,255,255,.08)':'transparent'}>
          <span style={{width:8,height:8,borderRadius:'50%',background:C.green,boxShadow:`0 0 8px ${C.green}`}}/>
          <span style={{fontSize:14,color:'rgba(200,230,200,.6)'}}>{userMeta?.name||authUser?.email}</span><span style={{fontSize:10,color:'rgba(200,230,200,.3)'}}>▾</span></div>
        {showUserMenu&&<div style={{position:'absolute',top:'100%',right:0,zIndex:500,background:'#0D0D1F',border:'1px solid rgba(255,255,255,.1)',borderRadius:6,overflow:'hidden',minWidth:180,marginTop:4,boxShadow:'0 8px 24px rgba(0,0,0,.5)'}}>
          {[['◈ Đổi mật khẩu',()=>{setShowChangePw(true);setShowUserMenu(false)},C.gold],['↩ Đăng xuất',logout,C.pink]].map(([l,fn,c])=><div key={l} onClick={fn} style={{padding:'12px 16px',cursor:'pointer',fontSize:14,color:c,borderBottom:'1px solid rgba(255,255,255,.05)'}} onMouseEnter={e=>e.currentTarget.style.background='rgba(255,255,255,.07)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}>{l}</div>)}</div>}
      </div>
    </div>
    <div ref={containerRef} style={{flex:1,display:'flex',overflow:'hidden',minHeight:0}}>
      {sidebar&&<div style={{width:220,background:'rgba(0,0,0,.38)',borderRight:'1px solid rgba(255,255,255,.06)',display:'flex',flexDirection:'column',flexShrink:0}}>
        <div style={{padding:'10px 14px',display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:'1px solid rgba(255,255,255,.05)'}}>
          <span style={{fontFamily:'Orbitron',fontSize:9,color:C.green,letterSpacing:'2px',opacity:.5}}>◈ PROJECTS</span>
          <span onClick={()=>setShowNewProj(true)} style={{color:C.green,cursor:'pointer',fontSize:20,opacity:.5,lineHeight:1}} onMouseEnter={e=>e.currentTarget.style.opacity='1'} onMouseLeave={e=>e.currentTarget.style.opacity='.5'}>+</span></div>
        <div style={{flex:1,overflow:'auto',padding:'4px 0'}}>
          {projects.length===0&&<div style={{padding:'18px 14px',color:'rgba(200,230,200,.22)',fontSize:13,lineHeight:2}}>Chưa có project.<br/><span onClick={()=>seedDemo(authUser.uid)} style={{color:C.green,cursor:'pointer',textDecoration:'underline'}}>Load demo</span></div>}
          {topP.map(p=><SidebarItem key={p.id} p={p} activePid={activePid} setActivePid={setActivePid} onDelete={deleteProject} children={subOf(p.id)}/>)}</div>
      </div>}
      {activeProject?<div style={{flex:1,display:'flex',overflow:'hidden',minWidth:0,padding:8,gap:0}}>
        {showInput&&<><Panel pk="input" style={{width:leftW,flexShrink:0}}><InputTab project={activeProject}/></Panel>{(showTable||showChart)&&<Divider onDrag={d=>setLeftW(w=>Math.max(180,Math.min(500,w+d)))}/>}</>}
        {(showTable||showChart)&&<div style={{flex:1,display:'flex',flexDirection:'column',overflow:'hidden',minWidth:0,gap:0}}>
          {showTable&&<Panel pk="table" style={showChart?{height:topH,flexShrink:0}:{flex:1}}><TableTab project={activeProject}/></Panel>}
          {showTable&&showChart&&<Divider vertical onDrag={d=>{const mx=(containerRef.current?.clientHeight||600)-64;setTopH(h=>Math.max(120,Math.min(mx-120,h+d)))}}/>}
          {showChart&&<Panel pk="chart" style={{flex:1,minHeight:80}}><ChartTab project={activeProject} advisorModel={advisorModel} onAdvisorSelect={setAdvisorModel}/></Panel>}
        </div>}
        {!showInput&&!showTable&&!showChart&&<div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',color:'rgba(200,230,200,.2)',fontSize:13}}>Bật panel bằng nút trên header</div>}
      </div>:<div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:14,color:'rgba(200,230,200,.22)'}}><div style={{fontFamily:'Orbitron',fontSize:13,letterSpacing:'3px'}}>CHỌN HOẶC TẠO PROJECT</div><Btn onClick={()=>setShowNewProj(true)}>+ Tạo project</Btn></div>}
    </div>
    {showNewProj&&<NewProjectModal projects={projects} uid={authUser?.uid} onClose={()=>setShowNewProj(false)}/>}
    {showChangePw&&<ChangePwModal user={userMeta} onClose={()=>setShowChangePw(false)}/>}
  </div>
}
